default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  host: localhost
  username: root
  password:
  # socket: /var/run/mysqld/mysqld.sock
  # socket: /tmp/mysql.sock
development:
  <<: *default
  database: elastic
test:
  <<: *default
  database: <%= ENV["DATABASE_NAME_TEST"] %>

staging:
  <<: *default

production:
  <<: *default
  database: review_films_production
